import typing

def clear_screen(color: int):
    ...

def set_pixel(x: int, y: int, color: int):
    ...

def get_pixel(x: int, y: int) -> int:
    ...

def fill_rect(x: int, y: int, width: int, height: int, color: int):
    ...

def set_palette_map(colors: list[int]):
    ...

def draw_sprite(screen_x: int, screen_y: int, sprite_x: int, sprite_y: int, width: int, height: int):
    ...

def sfx(arguments: list):
    ...

def load_high_score(name: str) -> typing.Any:
    ...

def save_high_score(name: str, score: typing.Any):
    ...
